version: '3.9'
services:
  api:
    build:
      context: ../../..
      dockerfile: src/Clean/Dockerfile
    image: clean-architecture-api:latest
    container_name: clean-architecture-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=AppDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clean-architecture-db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "select 1"]
      interval: 10s
      retries: 10
volumes:
  clean_data: {}
